# Generated by Django 4.2.7 on 2026-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_alter_blogpost_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descripton', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
