# Generated by Django 4.2.7 on 2026-02-10 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='title',
            new_name='title1',
        ),
    ]
